### ISSUE TITLE
Request - Vertex graphical selecting

### ISSUE THREAD

**Issue by rinart73** [niftools/nifskope#102]
When I select 'NiTriShapeData' block and in the Block Details select 'Verticles', I can see all verticles like dots. And they're highlighting (its hard to see, actually) when I choose some of them.

But it would be great to have the ability to select verticle in the preview window and after that get/set their position.

You may suggest me to use Blender, but NifSkope works with Skyrim nifs without any troubles. And Blender import/export is huge pain, considering lost of lighting, texturing e.t.c.

**Comment by hexabits** [comment]
This is already a feature.  Please see the changelog here:  https://github.com/jonwd7/nifskope/releases/tag/v2.0.dev5
