### ISSUE TITLE
FO4 is blue channel in specular used for subsurface scattering? ( Fallout Cascadia)

### ISSUE THREAD

**Issue by doodlum** [niftools/nifskope#107]
@jonwd7 iirc, looking at how NifScope handles the specmap, blue channel isn't used for anything.

While most specmaps in Fallout 4 don't have a blue channel, some do, particularly grass and plant textures. We know that subsurface scattering does seem to occur on grass, so is it possible the blue channel is for this? There's lots of confusion from people as to whether it is used or not. 

I'm a dev for http://www.falloutcascadia.com/ 
Since we are basically making a new game, we need to know as much about how the game works as possible, and need to be able to create all types of assets.

If you are willing to lend a hand with us, whenever we have issues that could be awesome.

https://discord.gg/yjTmyVQ here's a link to our community discord

**Comment by hexabits** [comment]
@Doodlezoid  I looked at _S maps which are not BC5 (@ousnius generated a list for me) and looked at some NIF files associated with them and they do seem to have Backlight Power set to a value greater than 0.0.  It would be safe to assume that the blue channel is the mask but you would need to create a test specular with a distinguishable test pattern in the blue channel.

Anyway speaking of Discord I made a niftools one last week. You and your team can join it if you like:   https://discord.gg/ZFjdN4x  I haven't linked it anywhere publicly until now but we'll be putting the link up on some things shortly.  It's a more appropriate place for questions such as this anyway.
