### ISSUE TITLE
Revert change which undid separate registry settings per version

### ISSUE THREAD

**Issue by hexabits** [niftools/nifskope#11]
We should possibly revert 2862caa which got rid of a separate registry group for each version.  Or more simply restore / improve on the behavior.

I ran into an issue where my installed version and dev version somehow corrupted the render view settings,  so I think it may be best to sort out some of the settings into a per-version registry entry again.

Some should be just shared across all versions, such as Texture Paths.
### Update

Currently, going from `1.2.0a1.dev19` to `1.2.0a1.dev20` will cause the UI to reset.  This is annoying for testers.

Upon looking into this further, the only reason the settings are cleared is not for differing _NifSkope_ versions, but differing _Qt_ versions.

Going forward, the Qt version should be stored in the settings alongside the NifSkope version.  Unfortunately, since the settings have been reduced to one setting group across NifSkope versions, there is no way to allow later versions of NifSkope to operate alongside 1.1.3 without each other clearing the settings.  Thus reverting back to settings groups for each version is necessary, or at the very least create a new settings group going forward, and abandon the old registry values and leave those for legacy versions. 

Settings that aren't binary (and thus Qt-version dependent) can still be migrated from pre-1.2.0 installations to a new registry location.

So, for new installations of NifSkope,  all registry values will be in the new locations.  For existing installations of NifSkope, the first time NifSkope is run, any settings that can be migrated will.  That way NifSkope 1.2.0+ will no longer see the pre-1.2.0 settings.
#### Tracking

Refactor Progress #32

**Comment by skyfox69** [comment]
Separating settings into a per-version registry sounds great. One thumb up for this!

Next to your 'Restore Defaults' I suggest a 'settings copy' from actual version to new version when creating registry entries for the new version. By this the user doesn't have to setup again and again with every new version. @jonwd7 And I think there's much to come since you're in charge now ;-)

**Comment by hexabits** [comment]
@skyfox69  Yeah, you can see the old migration code in 2862caa ... I think that maybe instead of keeping some settings (texture paths) version independent, that they could still all get migrated, but if you don't want some portion coming over to the new version, you can restore defaults to just that tab/category. 

So maybe instead of just one Restore (All) Defaults, it's split out into one Restore per settings section.   Only issue is that some of the registry keys have no explicit representation in the UI, e.g. Render View defaults.  So in the Render settings tab it may have to be clarified that Restore Defaults also clears camera defaults.  Or actually include options for the default camera mode / position (but that's for another issue # :smile:)

Then of course in addition to Restore Defaults per tab, have a Restore All for the lazy. :wink:

---

Another Idea:  Have settings per game/install?  I'm not well versed with Windows installers, but I would assume it's feasible.  I'm not sure what happens currently, when you try to install NifSkope more than once in different locations.

The installer could act similarly to 3ds Max plug-in installers, where you check each version you want to install for...

**Comment by neomonkeus** [comment]
NifSkope already has some auto-detection of game installs so you could look into that. I don't know what installer is used by NifSkope but I suspect that it is NSIS which is horrible to code.

But I suppose it is also a case of how easy it is to add new games and maintain that system as users tend to install in non-default locations

**Comment by hexabits** [comment]
Noting here that we've discussed having one single dev-specific registry entry created when using dev builds, regardless of version.

That way dev builds can be messed with without ruining your settings for the official release.

**Comment by hexabits** [comment]
Also, there's a typo for a registry entry. When list mode = "hirarchy".  Inconsequential, but I wanted to note it here.

I was thinking that the registry entry should include the install path for the EXE.  I noticed that the application awkwardly searches for some things like the XML files, the shaders/lang folders, etc.  It should first look in the current application directory, then look for the install path in the registry.

This would also help when the EXE is outside of its normal location like when we do dev builds,  though we could still integrate post-build processes into the NifSkope.pro file to copy those files over.
