### ISSUE TITLE
Invalid

### ISSUE THREAD

**Issue by Lukong15** [niftools/nifskope#110]
OH AND THANK YOU FOR BRINGING UP my last POST AFTER IT WAS CLOSE WITHOUT LEAVING ME THE ABILITY TO REPLY...YOU MUST BE MIND READERS.

Yes I can Press ENTER
Yes I can Press ENTER
Yes I can Press ENTER
Yes I can Press ENTER
 
WHAT ABOUT WHAT IS BELOW 29...OR MAYBE YOU CAN SEE THROUGH DISPLAYS!!!
HERE I THOUGHT YOU WERE DIFFERENT JONW7 based on your. last. post ("There might be something useful in there" sounds like you actually skim through it at least...instead of seeing more than 10 lines and clicked Closed). 
I WAS COMPLEMENTING YOUR POST on your grammar...thinking you misunderstood me when I mention the Flags & showing the Block Detail & Flags cause I didn't write it properly and notice you didn't point that out and GAVE YOU A COMPLEMENT for not being a Grammar Nazi, so I returned the Favour (BUT BASED ON THE "THIS ISN'T A FORUM" I made a Gitman joke).

ALSO BASED ON WHAT YOU SAID THE LAST TIME IT SEEM TO ME YOU WERE BEING NICE ENOUGH TO READ MY POST, SO I RETURN THE FAVOUR...

WTH ARE YOU ATTACKING ME THEN!!!

**Comment by Lukong15** [comment]
DO YOU READ! cause I'm looking for Tutorial on NifSkope's Nodes or Flags cause of my disappearing PA Armor, but I'm at not coming here and asking for help, just giving some info and bug reporting.

Also you were right about the Default though.

**Comment by Lukong15** [comment]
AND UNCHECKING IT DOESN'T MATTER, also if you think I unchecked it after all the screen shots. That is the first thing I did...then I took screenshots of the Flags Window to show proof of the change and mistake of not pointing out the Flag Window...then I thought also take a picture of your suggestion to show you if I followed the right way.

**Comment by neomonkeus** [comment]
Locking conversation.

**Comment by neomonkeus** [comment]
@Lukong15 This is not the first topic which had to be closed.
As previously stated this is not a forum, you have to be concise with request.

 The term "for your sanity" was used in the context of helping you by removing unnecessary information to make the situation easier. You have interpreted it differently, which is your choice but at no point was an implication of lack of intelligence or warrant the use of language which you did. As such the remarks have resulted in you been put on the banned list.
