### ISSUE TITLE
can not understand

### ISSUE THREAD

**Issue by dudethedude** [niftools/nifskope#111]
can not understand how to get Nifskope to download and install please help

**Comment by neomonkeus** [comment]
Please do not open a duplicate issue

**Comment by dudethedude** [comment]
im sorry didnt know how to change the title so people would understand but
could you help me on how to download and install nifskope because i dont
understand how to get the newest version i dont understand these Downloads

   - 8.1 MBNifSkope_2_0_2016-11-07.7z
   <https://github.com/niftools/nifskope/releases/download/v2.0.dev6/NifSkope_2_0_2016-11-07.7z>
   - Source code (zip)
   <https://github.com/niftools/nifskope/archive/v2.0.dev6.zip>
   - Source code (tar.gz)
   <https://github.com/niftools/nifskope/archive/v2.0.dev6.tar.gz>

**Comment by josephcrowell** [comment]
www.7-zip.org/download.html

**Comment by dudethedude** [comment]
thank you and again sorry
