### ISSUE TITLE
Alpha 6 Transform Edit Dialog Movement Broken

### ISSUE THREAD

**Issue by MeshHackingMonkey** [niftools/nifskope#117]
In previous versions if you right click NiTriShape > Transform > Edit and use mouse wheel or up/down arrows on any entry (translation, rotation, scale) in the dialog box the mesh object would move in real time according values input. This no longer works in alpha 6 for me, values change but object does not move until you do transform > apply. Makes it really hard to line up objects.

Roll back to alpha 5 function works again.

Anyone else have this issue?

**Comment by MeshHackingMonkey** [comment]
I guess I am only one with this issue or did I not explain enough?

**Comment by InsanePlumber** [comment]
I use version Alpha 6 and I work it without problems.

Try this.
https://github.com/niftools/nifskope/issues/118

**Comment by MeshHackingMonkey** [comment]
Thanks InsanePlumber, I did try clean install of A6 by clearing reg (reg key is recreated on first launch) and deleting folder contents per a post I saw you make on AFKmods  since posting so I tried that already and did not work, sorry should have said. As test I literally just swap the nifskope.exe leaving dev 6 contents and dev 5 works again as expected, swap back to A6 no luck, so does not seem like reg issue at least.

EDIT: I do want to make sure I am describing properly, the values in the boxes do change with mouse scroll or tiny up/down arrows but the object itself does not move in render window at same time.

**Comment by InsanePlumber** [comment]
If that's what you mean (GIF), it will work for me. (keyboard buttons up and down as well as mouse scroll)
http://i.imgur.com/TP3RtR0.gif

EDIT
On GIF should be LMB not RMB :P

**Comment by MeshHackingMonkey** [comment]
Thanks I really appreciate your effort, yes that is exactly what I mean. I guess I am just special then, will have to stick with A5 then as I cannot think of what would cause this if no one else can replicate :(

Is there a different runtime (.net or c++) required between the 2 builds?
I have .net 4.7 and 2005 thru 2015 c++ both x86 and x64 running win7pro, grasps at last straw...

**Comment by MeshHackingMonkey** [comment]
Found other user in niftools.org forum with same issue
https://forum.niftools.org/topic/4499-transform-gtedit-no-realtime-preview/

**Comment by hexabits** [comment]
As I've said elsewhere, there was nothing that changed on NifSkope's end that could have caused it to stop working.   Here it is working in dev7,  showing off a new button to Reject all the changes:  https://www.youtube.com/watch?v=ywsGvdEBKS4

You can join the Discord and try out the newer test builds to see if it works for you.

**Comment by MeshHackingMonkey** [comment]
Tried dev7 just now and it does not work either, the yellow node of the bone moves but not the object selected (skirt). If I hit Transform > Apply the object moves to the expected spot.

![nfd7](https://user-images.githubusercontent.com/30536316/31855917-e60feae8-b669-11e7-9b3c-2256fa93a109.png)

**Comment by hexabits** [comment]
.... You can't Transform skinned stuff in that way and it in fact warns you of this before the Edit dialog shows up.

**Comment by hexabits** [comment]
To clarify, certain transforms are ignored when a mesh is skinned.  And trying to modify the transform is likely not going to end up doing what you think.  In 2.0 dev6 I actually correctly skinned Skyrim models whereas they were not skinned before.  The colored bone icon in the render toolbar is indicating Skinning is enabled, which will show like how it should in game.   The reason nothing is visually happening is because the skinning is keeping it that way.

**Comment by MeshHackingMonkey** [comment]
Ahhh its the toolbar button, if I toggle that it move the object correctly as expected, thanks Jon. By the way love the new interface.

Issue solved.

**Comment by MeshHackingMonkey** [comment]
Ahhh it the toolbar button, if I toggle that then the object moves as expected, duh! Thanks Jon had no idea about that button. By the way love the new interface.
