### ISSUE TITLE
Nifscope 2.0 alpha . Was working fine for days, now suddenly crashes on startup

### ISSUE THREAD

**Issue by iloveicecream** [niftools/nifskope#118]
I've been using it fine for weeks, and was even using it early today. Now it crashes on startup (even without opening a nif) it just doesnt load and crashes. I havent changed anything. I've restarted computer several times and still having issue. Not sure what to do next.

**Comment by InsanePlumber** [comment]
Try deleting the contents of the Registry for NifSkope.
01 Create a TXT file.
02 Edit and add this content

---------------------------------------------------------------------------
Windows Registry Editor Version 5.00

[-HKEY_CURRENT_USER\Software\NifTools]

---------------------------------------------------------------------------

03 Save change the extension to "reg".
04 Run as Administrator.

**Comment by iloveicecream** [comment]
thank you that did the trick
