### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by theuser2** [niftools/nifskope#127]
It requires MSVCP140.dll

**Comment by hexabits** [comment]
Read the first line of the release.  This is not a bug.

**Comment by theuser2** [comment]
That doesn't help at all.

**Comment by hexabits** [comment]
This is not the place to ask questions.  This is an Issues page.  This is not an Issue, this is you being clueless.  We have a Discord and forums for those.   http://lmgtfy.com/?q=VC%2B%2B+2015+Redistributable
