### ISSUE TITLE
The important question of commercial use Nif scope!

### ISSUE THREAD

**Issue by AKSYON0V** [niftools/nifskope#132]
Good day, question is that some modmakers from Russia think that the file extension nif you can sell, from here a question: is it possible to do this? If the modmaker created his 3D model from scratch, then used Nif Scope and export plug-in for 3D editor of any of the available-is it allowed to sell a similar 3D model in the nif extension? Sorry if I write not on topic, but I think the developers and people working to improve the Nif Scope known the answers to these questions, thank you.

**Comment by Brandano** [comment]
I believe it's a bit complex. The model itself is the property of the author, so he can do with it whatever he likes. However, the file format specifications belong to the Gamebryo engine authors, that could probably bring some patent claims against any commercial use of the format. Whether such a claim would be valid or not, is difficult to say, but if they were to bring up a litigation it would likely just be to financially ruin the other party, and you don't really need to have a valid claim to do that. At the end of the day, it's safest not to try and build a commercial activity around the file format. But in practical terms it's like asking if you can sell data organized in Excel tables without having to pay a tithe to Microsoft, and I think that it would be perfectly legal to do so as long as you own the actual content.

On 13/02/2018 06:37, AKSYON0V wrote:

Good day, question is that some modmakers from Russia think that the file extension nif you can sell, from here a question: is it possible to do this? If the modmaker created his 3D model from scratch, then used Nif Scope and export plug-in for 3D editor of any of the available-is it allowed to sell a similar 3D model in the nif extension? Sorry if I write not on topic, but I think the developers and people working to improve the Nif Scope known the answers to these questions, thank you.

**Comment by AKSYON0V** [comment]
Thank you so much, I needed the other side's answer - since I'm confused about all this, now I know for a fact that my thoughts on this matter were true.  You helped me a lot, I think now I have to notify and other Russian-speaking modmakers that they are mistaken in this regard.

**Comment by hexabits** [comment]
Also GitHub is the last place for this question.  Any other place would have been acceptable.  This is to report software issues for NifSkope.
