### ISSUE TITLE
Hair is not displayed.

### ISSUE THREAD

**Issue by tktk11** [niftools/nifskope#133]
nifskope dev7 is the great update. But, hair is not displayed in Skyrim meshes. It is no problem with dev6. I try to mod NiAlphaProperty and BSLightingShaderProperty values, but nothing improved it. I think that there seems to be some fundamental problem.

**Comment by hexabits** [comment]
This is already fixed on test builds.  I haven't released it to GitHub yet.  https://afkmods.iguanadons.net/index.php?/topic/4136-nifskope-20-dev/&page=22&tab=comments#comment-171434

**Comment by tktk11** [comment]
Oh, I overlooked it. Thank you for continuing the development. It is very useful for my mod development.
