### ISSUE TITLE
Crashes to Desktop when using Wine on Linux.

### ISSUE THREAD

**Issue by WAR10CKfreeworld** [niftools/nifskope#137]
Application opens but then crashes immediately afterwards.
Here is the Wine Crash Log:
Unhandled exception: page fault on read access to 0x00000208 in 64-bit code (0x00007fe81cd9d407).
Register dump:
 rip:00007fe81cd9d407 rsp:0000000000229ed0 rbp:000000007d0dd0e0 eflags:00010246 (  R- --  I  Z- -P- )
 rax:0000000000000000 rbx:000000007f76a920 rcx:0000000000000000 rdx:0000000000000001
 rsi:0000000000000032 rdi:000000007f76a920  r8:0000000000000000  r9:0000000000000000 r10:0000000000000000
 r11:0000000000000000 r12:000000007d5fa0d0 r13:000000007d5f9c70 r14:0000000000000000 r15:0000000001328ab0
Stack dump:
0x0000000000229ed0:  0000000000000000 0000000000000000
0x0000000000229ee0:  0000000000000000 0000000000000000
0x0000000000229ef0:  0000000000000000 2e77c5382aca6600
0x0000000000229f00:  000000007d5f6750 000000007cf41490
0x0000000000229f10:  000000007d0aa9a0 2e77c5382aca6600
0x0000000000229f20:  000000007d5f9c70 000000007f76a920
0x0000000000229f30:  0000000000000032 0000000000000000
0x0000000000229f40:  000000007d5f9c70 0000000000000000
0x0000000000229f50:  0000000001328ab0 00007fe81cd7cc97
0x0000000000229f60:  000000007f76a924 0000000100000032
0x0000000000229f70:  00650070006f006b 0000000000004500
0x0000000000229f80:  000000000022a070 00007fe8217fdae0
Backtrace:
=>0 0x00007fe81cd9d407 in i965_dri.so (+0x3b8407) (0x000000007d0dd0e0)
  1 0x00007fe81cd7cc97 in i965_dri.so (+0x397c96) (0x0000000000000032)
  2 0x000000007a913ac9 glClear+0x98() in opengl32 (0x000000000022a070)
  3 0x00000001401be604 in nifskope (+0x1be603) (0x000000000022a180)
0x00007fe81cd9d407: movq	0x0000000000000208(%rax),%r15
Modules:
Module	Address					Debug info	Name (148 modules)
PE	          450000-          598000	Deferred        qwindows
PE	          b20000-          b62000	Deferred        qjpeg
PE	          b70000-          b7e000	Deferred        qtga
PE	          b80000-          bf4000	Deferred        qwebp
PE	        61000000-        61034000	Deferred        qt5xml
PE	        63000000-        63056000	Deferred        qt5opengl
PE	        64000000-        6410b000	Deferred        qt5network
PE	        65000000-        65549000	Deferred        qt5widgets
PE	        67000000-        6756c000	Deferred        qt5core
ELF	        7a800000-        7a9d2000	Dwarf           opengl32<elf>
  \-PE	        7a850000-        7a9d2000	\               opengl32
ELF	        7b400000-        7b80d000	Deferred        kernel32<elf>
  \-PE	        7b420000-        7b80d000	\               kernel32
ELF	        7bc00000-        7bd16000	Deferred        ntdll<elf>
  \-PE	        7bc20000-        7bd16000	\               ntdll
ELF	        7c000000-        7c004000	Deferred        <wine-loader>
PE	       140000000-       14038a000	Export          nifskope
PE	       180000000-       1805b4000	Deferred        qt5gui
ELF	    7fe81b6ae000-    7fe81b8e8000	Deferred        libtxc_dxtn.so
ELF	    7fe81b8e8000-    7fe81baf2000	Deferred        libpciaccess.so.0
ELF	    7fe81baf2000-    7fe81bd0d000	Deferred        libgpg-error.so.0
ELF	    7fe81c092000-    7fe81c29e000	Deferred        libdrm_radeon.so.1
ELF	    7fe81c29e000-    7fe81c4a6000	Deferred        libdrm_nouveau.so.2
ELF	    7fe81c4a6000-    7fe81c6c9000	Deferred        libdrm_intel.so.1
ELF	    7fe81c6c9000-    7fe81c9e5000	Deferred        libgcrypt.so.20
ELF	    7fe81c9e5000-    7fe81d2dd000	Dwarf           i965_dri.so
ELF	    7fe81d2dd000-    7fe81d4ef000	Deferred        libdrm.so.2
ELF	    7fe81d4ef000-    7fe81d6f4000	Deferred        libxcb-dri2.so.0
ELF	    7fe81d6f4000-    7fe81d90f000	Deferred        libxcb-glx.so.0
ELF	    7fe81d90f000-    7fe81db11000	Deferred        libx11-xcb.so.1
ELF	    7fe81db11000-    7fe81dd14000	Deferred        libxdamage.so.1
ELF	    7fe81dd14000-    7fe81df43000	Deferred        libglapi.so.0
ELF	    7fe81df43000-    7fe81e145000	Deferred        libxshmfence.so.1
ELF	    7fe81e145000-    7fe81e34c000	Deferred        libxcb-sync.so.1
ELF	    7fe81e34c000-    7fe81e54f000	Deferred        libxcb-present.so.0
ELF	    7fe81e54f000-    7fe81e753000	Deferred        libxcb-dri3.so.0
ELF	    7fe81e753000-    7fe81e9c5000	Deferred        libgl.so.1
ELF	    7fe81e9c5000-    7fe81ed2d000	Deferred        wined3d<elf>
  \-PE	    7fe81e9e0000-    7fe81ed2d000	\               wined3d
ELF	    7fe81ed2d000-    7fe81ef79000	Deferred        d3d9<elf>
  \-PE	    7fe81ed30000-    7fe81ef79000	\               d3d9
ELF	    7fe81ef79000-    7fe81f1b5000	Deferred        uxtheme<elf>
  \-PE	    7fe81ef80000-    7fe81f1b5000	\               uxtheme
ELF	    7fe81f30d000-    7fe81f52d000	Deferred        wintab32<elf>
  \-PE	    7fe81f310000-    7fe81f52d000	\               wintab32
ELF	    7fe81f54f000-    7fe81f755000	Deferred        libxfixes.so.3
ELF	    7fe81f755000-    7fe81f95f000	Deferred        libxcursor.so.1
ELF	    7fe81f95f000-    7fe81fb6f000	Deferred        libxi.so.6
ELF	    7fe81fb6f000-    7fe81fd72000	Deferred        libxcomposite.so.1
ELF	    7fe81fd72000-    7fe81ff7d000	Deferred        libxrandr.so.2
ELF	    7fe81ff7d000-    7fe820187000	Deferred        libxrender.so.1
ELF	    7fe820187000-    7fe82038d000	Deferred        libxxf86vm.so.1
ELF	    7fe82038d000-    7fe820590000	Deferred        libxinerama.so.1
ELF	    7fe820590000-    7fe820798000	Deferred        librt.so.1
ELF	    7fe820798000-    7fe8209ad000	Deferred        libbsd.so.0
ELF	    7fe8209ad000-    7fe820bb3000	Deferred        libxdmcp.so.6
ELF	    7fe820bb3000-    7fe820db7000	Deferred        libxau.so.6
ELF	    7fe820db7000-    7fe820fdf000	Deferred        libxcb.so.1
ELF	    7fe820fdf000-    7fe82131d000	Deferred        libx11.so.6
ELF	    7fe82131d000-    7fe82152f000	Deferred        libxext.so.6
ELF	    7fe82156a000-    7fe821809000	Deferred        winex11<elf>
  \-PE	    7fe821580000-    7fe821809000	\               winex11
ELF	    7fe821809000-    7fe821b87000	Deferred        oleaut32<elf>
  \-PE	    7fe821830000-    7fe821b87000	\               oleaut32
ELF	    7fe821b87000-    7fe821db4000	Deferred        msacm32<elf>
  \-PE	    7fe821b90000-    7fe821db4000	\               msacm32
ELF	    7fe821db4000-    7fe822077000	Deferred        winmm<elf>
  \-PE	    7fe821dc0000-    7fe822077000	\               winmm
ELF	    7fe822077000-    7fe82237e000	Deferred        msvcr120<elf>
  \-PE	    7fe8220a0000-    7fe82237e000	\               msvcr120
ELF	    7fe82237e000-    7fe82259d000	Deferred        concrt140<elf>
  \-PE	    7fe822380000-    7fe82259d000	\               concrt140
ELF	    7fe82259d000-    7fe8227c3000	Deferred        imm32<elf>
  \-PE	    7fe8225a0000-    7fe8227c3000	\               imm32
ELF	    7fe822809000-    7fe822a3b000	Deferred        libexpat.so.1
ELF	    7fe822a3b000-    7fe822c80000	Deferred        libfontconfig.so.1
ELF	    7fe822c80000-    7fe822e9a000	Deferred        libz.so.1
ELF	    7fe822e9a000-    7fe8230cd000	Deferred        libpng16.so.16
ELF	    7fe8230cd000-    7fe823382000	Deferred        libfreetype.so.6
ELF	    7fe823382000-    7fe8235ac000	Deferred        libtinfo.so.5
ELF	    7fe8235ac000-    7fe8237d0000	Deferred        libncurses.so.5
ELF	    7fe8237d0000-    7fe8239e5000	Deferred        api-ms-win-crt-convert-l1-1-0<el
PE	    7fe8237e0000-    7fe8239e5000	Deferred        api-ms-win-crt-convert-l1-1-0
ELF	    7fe8239e5000-    7fe823cc9000	Deferred        crypt32<elf>
  \-PE	    7fe8239f0000-    7fe823cc9000	\               crypt32
ELF	    7fe823cc9000-    7fe823ef6000	Deferred        iphlpapi<elf>
  \-PE	    7fe823cd0000-    7fe823ef6000	\               iphlpapi
ELF	    7fe823ef6000-    7fe824129000	Deferred        netapi32<elf>
  \-PE	    7fe823f00000-    7fe824129000	\               netapi32
ELF	    7fe824129000-    7fe824340000	Deferred        libresolv.so.2
ELF	    7fe824340000-    7fe824561000	Deferred        dnsapi<elf>
  \-PE	    7fe824350000-    7fe824561000	\               dnsapi
ELF	    7fe824561000-    7fe824774000	Deferred        api-ms-win-crt-locale-l1-1-0<elf
PE	    7fe824570000-    7fe824774000	Deferred        api-ms-win-crt-locale-l1-1-0
PE	    7fe824774000-    7fe824988000	Deferred        api-ms-win-crt-filesystem-l1-1-0
PE	    7fe824780000-    7fe824988000	Deferred        api-ms-win-crt-filesystem-l1-1-0C:\windows\system32\api-ms-win-crt-filesystem-l1-1-0.dll
ELF	    7fe824988000-    7fe824b9c000	Deferred        api-ms-win-crt-time-l1-1-0<elf>
  \-PE	    7fe824990000-    7fe824b9c000	\               api-ms-win-crt-time-l1-1-0
ELF	    7fe824b9c000-    7fe824db2000	Deferred        api-ms-win-crt-string-l1-1-0<elf
PE	    7fe824ba0000-    7fe824db2000	Deferred        api-ms-win-crt-string-l1-1-0
ELF	    7fe824db2000-    7fe824fc7000	Deferred        api-ms-win-crt-stdio-l1-1-0<elf>
  \-PE	    7fe824dc0000-    7fe824fc7000	\               api-ms-win-crt-stdio-l1-1-0
ELF	    7fe824fc7000-    7fe8251e0000	Deferred        api-ms-win-crt-math-l1-1-0<elf>
  \-PE	    7fe824fd0000-    7fe8251e0000	\               api-ms-win-crt-math-l1-1-0
ELF	    7fe8251e0000-    7fe8253f4000	Deferred        api-ms-win-crt-heap-l1-1-0<elf>
  \-PE	    7fe8251f0000-    7fe8253f4000	\               api-ms-win-crt-heap-l1-1-0
PE	    7fe8253f4000-    7fe825607000	Deferred        api-ms-win-crt-environment-l1-1-
PE	    7fe825400000-    7fe825607000	Deferred        api-ms-win-crt-environment-l1-1-C:\windows\system32\api-ms-win-crt-environment-l1-1-0.dll
ELF	    7fe825607000-    7fe82581b000	Deferred        api-ms-win-crt-utility-l1-1-0<el
PE	    7fe825610000-    7fe82581b000	Deferred        api-ms-win-crt-utility-l1-1-0
ELF	    7fe82581b000-    7fe825a30000	Deferred        api-ms-win-crt-runtime-l1-1-0<el
PE	    7fe825820000-    7fe825a30000	Deferred        api-ms-win-crt-runtime-l1-1-0
ELF	    7fe825a30000-    7fe825c46000	Deferred        vcruntime140<elf>
  \-PE	    7fe825a40000-    7fe825c46000	\               vcruntime140
ELF	    7fe825c46000-    7fe825f59000	Deferred        ucrtbase<elf>
  \-PE	    7fe825c70000-    7fe825f59000	\               ucrtbase
ELF	    7fe825f59000-    7fe826293000	Deferred        msvcp140<elf>
  \-PE	    7fe825f90000-    7fe826293000	\               msvcp140
ELF	    7fe826293000-    7fe8264be000	Deferred        mpr<elf>
  \-PE	    7fe8262a0000-    7fe8264be000	\               mpr
ELF	    7fe8264be000-    7fe8266ff000	Deferred        ws2_32<elf>
  \-PE	    7fe8264d0000-    7fe8266ff000	\               ws2_32
ELF	    7fe8266ff000-    7fe82698c000	Deferred        shlwapi<elf>
  \-PE	    7fe826710000-    7fe82698c000	\               shlwapi
ELF	    7fe82698c000-    7fe826e1b000	Deferred        shell32<elf>
  \-PE	    7fe8269b0000-    7fe826e1b000	\               shell32
ELF	    7fe826e1b000-    7fe8270b0000	Deferred        rpcrt4<elf>
  \-PE	    7fe826e30000-    7fe8270b0000	\               rpcrt4
ELF	    7fe8270b0000-    7fe827451000	Deferred        ole32<elf>
  \-PE	    7fe8270e0000-    7fe827451000	\               ole32
ELF	    7fe827451000-    7fe82766b000	Deferred        version<elf>
  \-PE	    7fe827460000-    7fe82766b000	\               version
ELF	    7fe82766b000-    7fe827aa7000	Deferred        user32<elf>
  \-PE	    7fe827690000-    7fe827aa7000	\               user32
ELF	    7fe827aa7000-    7fe827d37000	Deferred        advapi32<elf>
  \-PE	    7fe827ac0000-    7fe827d37000	\               advapi32
ELF	    7fe827e37000-    7fe8281b2000	Deferred        gdi32<elf>
  \-PE	    7fe827e50000-    7fe8281b2000	\               gdi32
ELF	    7fe8282b2000-    7fe8284c4000	Deferred        libnss_files.so.2
ELF	    7fe8284c4000-    7fe8286dc000	Deferred        libnsl.so.1
ELF	    7fe8286dc000-    7fe8288e8000	Deferred        libnss_nis.so.2
ELF	    7fe8288e8000-    7fe828af0000	Deferred        libnss_compat.so.2
ELF	    7fe828d20000-    7fe828f38000	Deferred        libgcc_s.so.1
ELF	    7fe828f38000-    7fe8292cb000	Deferred        libm.so.6
ELF	    7fe8292cb000-    7fe8294cf000	Deferred        libdl.so.2
ELF	    7fe8294cf000-    7fe829889000	Deferred        libc.so.6
ELF	    7fe829889000-    7fe829aa7000	Deferred        libpthread.so.0
ELF	    7fe829e4c000-    7fe82a073000	Deferred        ld-linux-x86-64.so.2
Threads:
process  tid      prio (all id:s are in hex)
0000000e services.exe
	00000022    0
	0000001d    0
	00000015    0
	00000014    0
	00000013    0
	00000010    0
	0000000f    0
00000011 winedevice.exe
	0000001c    0
	00000019    0
	00000018    0
	00000017    0
	00000016    0
	00000012    0
0000001a plugplay.exe
	0000001f    0
	0000001e    0
	0000001b    0
00000020 winedevice.exe
	0000002b    0
	00000026    0
	00000025    0
	00000024    0
	00000023    0
	00000021    0
00000027 explorer.exe
	0000002e    0
	0000002d    0
	0000002c    0
	00000028    0
00000029 (D) Z:\home\WAR10CK\Downloads\Mods\Modding Tools\Nifskope\NifSkope_2_0_2018-02-22-x64\NifSkope.exe
	00000030    0
	0000002f   15
	0000002a    0 <==
System information:
    Wine build: wine-3.0 (Debian 3.0-1)
    Platform: x86_64
    Version: Windows XP
    Host system: Linux
    Host version: 4.6.0-kali1-amd64

**Comment by hexabits** [comment]
Wine is not supported, esp. not mimicking Windows XP.  Use the actual Linux version.  You will have to compile it yourself unless someone made a build script for your distro.  There are compilation instructions in the wiki.

**Comment by neomonkeus** [comment]
You can grab the last merge build from - https://travis-ci.org/niftools/nifskope
