### ISSUE TITLE
ASSERT bhkListShape error

### ISSUE THREAD

**Issue by skinjack** [niftools/nifskope#140]
You'll have to pardon me as I know very little about Nifskope beyond what I use it for while creating weapons.

I recently delved into doing bows for Skyrim. However, I am now getting an ASSERT error as follows:
ASSERT
File:..\..\bhkListShape.cpp
Line: 269
NULL hkObject found in list shape

No clue what this means or even how to find it as I don't have line numbers anywhere. I've found bhkListShape under bhkCollisionObject, but there is no hkObject or NULL value that I can see. I do have a greyed out Material\HavokMaterial, but I don't know if that is normal or not.

Any clues why this is occurring? I am literally at a standstill until I figure this out, because the new .nif that I put into the Creation Kit causes it to crash to my desktop. I know the nif is correct, but I'm stumped why I'm getting this error. At first I thought I accidentally edited one of the vanilla weapon nifs and messed it up, but I'm getting this ASSERT no matter which vanilla nif I use.

If you need the files to try to reproduce the error I can make them available. I'm going to release them eventually anyway.

Any help would be greatly appreciated.

**Comment by hexabits** [comment]
GitHub Issues is not the place to ask for help with fixing NIFs that have been made incorrectly by the user.  We have a Discord and forums for that. 

What you are reporting is a symptom of you setting up the collision data incorrectly, not anything to do with NifSkope erroring.   Also the CK's crashes and their warning messages don't map exactly to the way we show the data, considering at the point it crashes the NIF has already been serialized into the game's classes for it which are different from the data on disk.

**Comment by skinjack** [comment]
Well, I'm not sure how I did the collision wrong since I copied it from a vanilla game nif, but I appreciate your response. And I'm sorry about the wrong forums. This is where I got directed. But then again, I had to open an account to ask my question, so maybe there was a mix-up in the links. Again, thank you. I'll re-check the nif.

**Comment by hexabits** [comment]
Copying blocks from a vanilla NIF is not immune to user error.  It's one of the easier ways to break a NIF in fact.  Without a screenshot of the structure or the NIF itself, I can't even begin to tell you the possible ways in which your NIF is wrong because there are so many ways to paste blocks into a NIF incorrectly.  But as I said this is not the place for 1-on-1 help with bad NIFs.  You'll want to ask in modding support on our Discord.
