### ISSUE TITLE
noobs

### ISSUE THREAD

**Issue by dcarmichiel** [niftools/nifskope#141]
how about you fucking superbrains just build a fucking installer or make a fucking patch for us people that dont want nor have the fuclking time to learn all this fucking crap, untill this 2.0 fucking build your nifskope was a great fucking tool.now it is a peice of shit that i have to maunally open every FUCKING TIME since it will no longer admit it is in a fucking windows enviroment and allow itself to be fucking associated with anything,thanks for all the years of a great tool 
fuck you for this latest peice of crap

**Comment by robboten** [comment]
wow. How about you fuck off?

**Comment by ghost** [comment]
Someone doesn't know how to windows.

**Comment by oeliza** [comment]
:snig:

**Comment by randprint** [comment]
[Search your registry for anything nifskope and clean all the old entries from the old installer and try again genius.](https://cdn.discordapp.com/attachments/309994957169623045/442071087707193355/unknown.png)

also, I'll just leave this here http://www.catb.org/esr/faqs/smart-questions.html

**Comment by Serithi** [comment]
How do you manage to be this inept at using Windows or googling fixes for issues?
