### ISSUE TITLE
Crash to Desktop

### ISSUE THREAD

**Issue by Thundertushy** [niftools/nifskope#145]
Hello,

I replied to an earlier post by Antreus, but not certain if it's been seen.  Reposting here as a new issue.  

My NifSkope 2.0 dev 7 is crashing as well. Tried the batch file posted [here](https://github.com/niftools/nifskope/files/2088266/OpenGL.Desktop.zip) , and it still crashes on start. Here's the crash details:

Problem signature:
Problem Event Name:	APPCRASH
Application Name:	NifSkope.exe
Application Version:	0.0.0.0
Application Timestamp:	5a8f8f4e
Fault Module Name:	atig6txx.dll
Fault Module Version:	24.20.11016.4
Fault Module Timestamp:	5afc7b82
Exception Code:	c0000005
Exception Offset:	000000000001a0cb
OS Version:	6.1.7601.2.1.0.256.1
Locale ID:	4105
Additional Information 1:	6ebc
Additional Information 2:	6ebcab7c419993445e9398a4fa6901cc
Additional Information 3:	898c
Additional Information 4:	898c33bf033344ed58a10d4fe7009038

The atig6txx.dll file seems to be from my AMD video card drivers.  I'm running AMD reference drivers, Adrenalin Edition v 18.5.1, release date ~ May 6 2018(?). Dunno why, but it looks like my version was replaced by v18.5.2: I don't see v18.5.1 available for download anymore.

18.5.2 link
https://support.amd.com/en-us/download/desktop/previous/detail?os=Windows%207%20-%2064&rev=18.5.2

**Comment by Thundertushy** [comment]
Ugh... ok, issue is no longer present.  No system changes have occurred; the issue survived several reboots, but I just randomly tried starting it now, and it's working.  Very odd behaviour.  Will investigate as possible hardware issue.  Will update if it reoccurs, but otherwise consider this pending closed.

**Comment by neomonkeus** [comment]
Closing as no response from reporter
