### ISSUE TITLE
BSWaterShaderProperty

### ISSUE THREAD

**Issue by hexabits** [niftools/nifskope#15]
NifSkope still gives a warning:

> Unknown property:  "BSWaterShaderProperty"

Should at least make the warning go away, if not try to improve support for it also.

**Comment by hexabits** [comment]
#### Commit Details

jonwd7/nifskope@9b72167

**Comment by ttl269** [comment]
@jonwd7 Same warning produces also `BSDistantTreeShaderProperty`, `BSSkyShaderProperty`, `DistantLODShaderProperty`, `HairShaderProperty`, `Lighting30ShaderProperty`, `NiDitherProperty`, `NiFogProperty`, `NiMultiTextureProperty`, `NiShadeProperty`, `NiTextureModeProperty`, `NiTransparentProperty`, `SkyShaderProperty`, `TallGrassShaderProperty`, `TileShaderProperty`, `VolumetricFogShaderProperty`, `WaterShaderProperty`.

**Comment by neomonkeus** [comment]
Created #78 with the information posted by @ttl269, this issue can be kept as just for supporting BSWaterShaderProperty.
