### ISSUE TITLE
Updated release for 2020?

### ISSUE THREAD

**Issue by Darklocq** [niftools/nifskope#169]
Last release seems to have been in 2017, but the change log shows important fixes since then. Neither the Discord nor Forum.NifTools.org links work any longer.  While I could theoretically clone this repo and compile it, I'm not normally a Windows user and likely don't have the right tools or their prerequisites, nor any experience compiling for Windows (I play and mod Skyrim in a Win10 VM on a Mac).  If the commits since the last release in 2017 are stable enough at least for some testing, a new 2020-01 dev release would likely be in order.  :-)

**Comment by hexabits** [comment]
The last release here links directly to my releases, which are newer.

**Comment by Darklocq** [comment]
Thanks, I will check that out.
