### ISSUE TITLE
BSFurnitureMarkerNode→Positions→Positions→Heading: Values not working properly

### ISSUE THREAD

**Issue by Outerspacespecies** [niftools/nifskope#177]
Which values must I type in to get an exact heading? The "Interactive Help" says the heading to be "Similar to Orientation, in float form", but no matter what value I enter, the result never corresponds to the intended orientation (well, there's one exception: the value zero).

Btw, thank you very very much for this powerful tool, Nifskope is awesome!

**Comment by Outerspacespecies** [comment]
PS: Just noticed that 180° seems to correspond to the value of π, thus an exact heading would be impossible?

**Comment by neomonkeus** [comment]
In computer graphic rotations are generally done in Radians rather than Degrees.
You can use a degree to radians converter to convert from the value that you want to be in Degrees to get the corresponding radian value.

**Comment by hexabits** [comment]
> thus an exact heading would be impossible

Being exactly 90 degrees vs being 89.9999 degrees doesn't remotely matter.  Actually, being 89.9999 is better because it would prevent things like gimbal lock. 

Given the nature of floating point, almost no value is "exact" either.

**Comment by Outerspacespecies** [comment]
Thanks, that helps me very much!!! 👍
