### ISSUE TITLE
Nothing Showing Up

### ISSUE THREAD

**Issue by V0guee** [niftools/nifskope#207]
Hey!

Not sure if I'm doing something wrong but whenever I try to import a .nif file into Blender, all that shows up are some points- no objects have loaded in or textures.

**Comment by neomonkeus** [comment]
Nifskope is a data viewer and editor, nothing todo with Blender, nor the corresponding addon that we have created. 

I would suggest ensuring that you have the latest version of the [Blender Niftools Addon](https://github.com/niftools/blender_niftools_addon/releases )
If you docontinue to have an issue, then you should open it on there, ensuring that you fill in the template, supplying requested information to help us diagnose and reproduce.
