### ISSUE TITLE
MacOS version not displaying texture

### ISSUE THREAD

**Issue by DigitalBox98** [niftools/nifskope#234]
I've been able to have Nifskope working on MacOS, however not able to have the texture displayed for any NIF (while the windows version is displaying fine the same NIF).

I'm currently investigating on MacOS, unfortunately for an unknown reason the debugger is not working fine on my Mac computer while it's OK on Windows (on other OpenGL projects the Mac debugger is OK, so I guess it's relative to the project :/)

Any tricks would be appreciated, I can only debug on windows to identify where the issue is on Mac for the moment.

<img width="956" alt="nifskope_mac" src="https://github.com/niftools/nifskope/assets/57635141/4df2ef15-f329-42e1-8d38-96aa6cf5a619">

**Comment by DigitalBox98** [comment]
It seems to be DDS format not recognized. When I convert DDS texture  to TGA it's working fine, so I'm closing this issue.

<img width="1218" alt="Capture d’écran 2024-01-29 à 11 57 33" src="https://github.com/niftools/nifskope/assets/57635141/7732b6a9-a0db-48b4-9044-0b12ce6b6988">

**Comment by digitalbox94** [comment]
Latest version for MacOS available here : https://github.com/digitalbox94/nifskope/releases/tag/v2.0.dev9

**Comment by tom8788** [comment]
Doest that mean you have to convert ALL mat files to TGA?

**Comment by DigitalBox98** [comment]
You can try on your side but yes for the moment
