### ISSUE TITLE
Qt 5 Port

### ISSUE THREAD

**Issue by hexabits** [niftools/nifskope#28]
Qt 4.8 is becoming antiquated. Porting to Qt 5 will ease some issues regarding compilation, by having more current tools and packages to work with.  There are of course many other benefits but it is pointless listing them.

I have already begun, but there currently a few issues.  I disabled a few non-essential elements temporarily.  These are due to some methods and classes going obsolete.
### Issues

See: 
- [C++ Api Changes](https://qt-project.org/doc/qt-5.0/qtdoc/sourcebreaks.html)
- [Transition from Qt 4.x to Qt 5](http://qt-project.org/wiki/Transition_from_Qt_4.x_to_Qt5)
- [Porting from Qt 4 to Qt 5](http://www.kdab.com/porting-from-qt-4-to-qt-5/)
##### QFSFileEngine, QAbstractFileEngine, QAbstractFileEngineIterator, and QAbstractFileEngineHandler are no longer public.

This is the basis of the FSEngine code, and the way of opening resources (BSAs).  Some alternative needs to be found.

~~**Update:**  I believe we are going to decide to take this out for the time being.  It didn't appear fully implemented to begin with, and as far as I could tell only allowed you to treat _uncompressed_ BSAs as if they were a directory, therefore accessing textures for the models without needing the loose files.~~

---
##### QSystemLocale is not public anymore. `RESOLVED`

This is a non-issue.  `NifSystemLocale` extends this class, but as far as I can tell it's never actually used.  If it were to be used `QLocale` is an option.
##### toAscii() and fromAscii() Methods are deprecated `RESOLVED`

Simple enough.  Just replace with `toLatin1()` / `fromLatin1()`.
##### QIcon() constructor changes `RESOLVED`

You can no longer give QIcon() a raw string.  You must wrap it with a QPixMap() constructor.
###### Affected Methods/Files:
- spells/headerstring.cpp@L73
- spells/light.cpp@L61
- spells/material.cpp@L101
- spells/stringpalette.cpp@L78
- spells/texture.cpp@L157
- spells/transform.cpp@L277
- widgets/colorwheel.cpp@L118
##### QWidget::setShown() is no longer forwarded to ::setVisible() `RESOLVED`

QWidget::setShown() is part of an ancient Qt3Support API which no longer exists as of Qt5. 
###### Affected Files:
- widgets/valueedit.cpp
##### QObject::trUtf8 and QCoreApplication::Encoding enums are deprecated. `RESOLVED`

~~There is one location in the code where this applies, and the solution is simply removing that parameter as it's now that way be default.  So a non-issue.~~  I can't even find where I made this change in the code...  :thought_balloon:   I know that it was an issue during compile, but I've scoured through every change in my commits and I can't seem to find it.

These above issues are all forward-compatible changes.  They could be fixed in the Qt 4 branch.

---
#### Miscellaneous

There are a few other odd errors I need to look into.  I will comment on these below.
#### Tracking

Refactor Progress #32

**Comment by hexabits** [comment]
#### QApplication changes  `RESOLVED`

[nifskope.cpp@L1309](https://github.com/jonwd7/nifskope/commit/7b9354a3a33788025063ab91f87ceffa5e2be331#diff-32caa590264aca8365121c9e1bf1c17dL1309)

``` C++
fname = QDir::current().filePath( app.argv()[ app.argc() - 1 ] );
```

I don't quite understand the source of the error here yet. It complains that QApplication does not have member methods argv() or argc(). (I'm quoting that from memory, might be slightly different)

#### Changes to QAbstractItemModel::reset()  `RESOLVED`

See: [Compatibility Members for QAbstractItemModel](http://qt-project.org/doc/qt-5.0/qtcore/qabstractitemmodel-compat.html)  

It appears that you can no longer call reset() on the QAbstractItemModel itself.  You instead wrap your reset code in a `beginResetModel()` / `endResetModel()` block.  The `endResetModel()` method emits the private signal which says the data has been changed.

##### Affected Methods/Files:
- `KfmModel::clear()` in kfmmodel.cpp@L86
- `KfmModel::load( QIODevice & device )` in kfmmodel.cpp@L238
- `NifModel::reset()` in nifmodel.cpp@L1466
- `NifProxyModel::reset()` nifproxy.cpp@L244

I have made **_tentative changes**_ to these files.  I have no idea if the changes I made are sane and they must be looked into carefully.

**Comment by hexabits** [comment]
#### Progress

##### Initial Commit: jonwd7/nifskope@7b9354a3a33788025063ab91f87ceffa5e2be331

Everything is actually working fairly well....  ~~Except the primary shape rendering.  Havok rendering works,  `drawSelection()` / `Node::SELECTING` rendering works, but during `drawShapes();` an exception is thrown.   Tracking it down now.~~  **SOLVED** (tentatively) ...  I wasn't invocating the current context for QOpenGLFunctions correctly.

##### Fixed remaining OpenGL issues: jonwd7/nifskope@7d4882e

##### Replaced QDirModel with QFileSystemModel: jonwd7/nifskope@3e3dd74

I had to replace `QDirModel` with `QFileSystemModel`.  The former was deprecated even BEFORE Qt 4.8.3...  For whatever reason in Qt 5 the QDirModel was no longer filtering filetypes correctly in the Load/Save As windows.  Meaning that all files were shown regardless of what was chosen in the file filter dropdown.

##### Switch from QGLContext to QOpenGLContext: jonwd7/nifskope@5ed1498

##### Store QOpenGLFunctions/Contexts on instances: jonwd7/nifskope@8709ca3

##### Fixed file dragging / double clicking: jonwd7/nifskope@9cc14a2

##### Fix OpenGL errors with multiple windows: jonwd7/nifskope@224b412

##### Fix for Qt 5 port of qDefaultMsgHandler: jonwd7/nifskope@7b43501

##### QFileDialog Filter fix (So they actually filter): jonwd7/nifskope@6ca3d87

**Comment by hexabits** [comment]
Re:  the main unresolved issue:

``` C++
fname = QDir::current().filePath( app.argv()[ app.argc() - 1 ] );
```

changing it to:

``` C++
fname = QDir::current().filePath( argv[ argc - 1 ] );
```

Works at first glance.  The pathname produced appears sane.  However, it reveals a larger issue.  The `fname` eventually gets passed to execCommand/sendCommand like so:

``` C++
ipc->execCommand( QString( "NifSkope::open %1" ).arg( fname ) )
```

When double-clicking on the EXE, `fname` is blank.  If double-clicking a NIF or dragging a NIF to the executable, `fname` is the path to the NIF. 

Opening the file utilizes UDP (sockets), therefore `fname` gets turned into a `QUrl` at some point.  It appears that as of Qt 5, it encodes the string like a URL, e.g. backslashes become `%5C`, thus opening a file actually breaks. 

Related Methods:
- `IPCsocket::execCommand( const QString & cmd )`
- `IPCsocket::sendCommand( const QString & cmd )`
- `IPCsocket::openNif( const QUrl & url )`
- `NifSkope::createWindow( const QString & fname )`

I created an overload for `openNif()` and I can drag a file to the EXE and it will open that file correctly.  Unfortunately there are two additional problems:
1. Dragging a second file to the EXE crashes the program.
2. Going to File > New Window creates a new window, but there are GL_ERROR (paint) invalid operations.  If you load a NIF with this window, it crashes the program.

I'm tracking down the source of these secondary issues, though they appear to be one in the same.

---

Update:  I'm done trying for the night, but it looks like it's something that is inherently different about Qt's in-built GL wrapper versus GLEW/GLee.  I attempted again to reintegrate GLEW, and despite everything on the internet telling me otherwise I was still unable to keep `qopenglfunctions.h` from being included and undefining some of the GLEW defines.

**Comment by hexabits** [comment]
I've very quickly, messily, and dirtily split the code into two different paths, one for QOpenGLFunctions/Contexts, and one for GLEW.  For the GLEW defines that Qt undefines, I manually resolve the function.

This means I can switch between GLEW and non-GLEW at will now with `CONFIG += glew`

**_UNFORTUNATELY**_...  the same problem exists in the GLEW code path.  GL paint errors upon creating a new window, only in that new window.  The previous window remains functional.  In addition I get a GL init error:  `GL ERROR (init): invalid enumerant`.

However, a commit or two ago, I managed to stop the actual crashing upon loading a 2nd mesh in a new window.  I now just get the GL paint errors and nothing displays.

I'm guessing it's still a GL issue and not down to some other code that broke between Qt 4 and Qt 5, like how the NIF data models get loaded, etc.  The actual model data appears fine in list/tree view (now that it's no longer crashing).

I'm about ready to consider rewriting the entire widget.

Qt is currently at a weird midway point between phasing out the QGL\* classes in favor of QOpenGL\* ones.  This means that QGLWidget is actually reaching its end of life.  Unfortunately there is not yet a QOpenGLWidget.  However there are a few new classes which will replicate the widget:

[OpenGL Window Example](https://qt-project.org/doc/qt-5.0/qtgui/openglwindow.html)

It involves the new `QWindow` and `QSurface` classes in Qt 5.

**Comment by hexabits** [comment]
OK, well I noticed something several commits ago, and it has something to do with the `QGLFormat` and the version/profile of OpenGL used.  So anyway I still wanted to see if GLEW had the same issue, and it did, so I revisited messing with the `QGLFormat` and it turns out I was right.  Here is that I left in the comments a few commits ago:

```
    /*
    // TODO:  As I create New Windows, the format changes
     1st
        QGLFormat(options QFlags(0x1|0x2|0x4|0x20|0x80|0x200|0x400) , plane  0 , depthBu
        fferSize  -1 , accumBufferSize  -1 , stencilBufferSize  -1 , redBufferSize  -1 ,
        greenBufferSize  -1 , blueBufferSize  -1 , alphaBufferSize  -1 , samples  -1 ,
        swapInterval  -1 , majorVersion  2 , minorVersion  0 , profile  0 )
        QObject(0x0)

     2nd
        QGLFormat(options QFlags(0x1|0x2|0x4|0x8|0x20|0x80|0x200|0x400) , plane  0 , dep
        thBufferSize  24 , accumBufferSize  -1 , stencilBufferSize  8 , redBufferSize  8
        , greenBufferSize  8 , blueBufferSize  8 , alphaBufferSize  8 , samples  4 , sw
        apInterval  -1 , majorVersion  4 , minorVersion  3 , profile  0 )
        GLView(0x3b4f250)

     3rd
        QGLFormat(options QFlags(0x1|0x2|0x4|0x8|0x20|0x80|0x200|0x400) , plane  0 , dep
        thBufferSize  24 , accumBufferSize  -1 , stencilBufferSize  8 , redBufferSize  8
        , greenBufferSize  8 , blueBufferSize  8 , alphaBufferSize  8 , samples  4 , sw
        apInterval  -1 , majorVersion  4 , minorVersion  3 , profile  1 )
        GLView(0x622a238)
    */
```

So, I attempted:

``` C++
GLView * GLView::create()
{
    ...
    fmt.setVersion(4, 3);
    fmt.setProfile(QGLFormat::CoreProfile);
    ...
```

To match the QGLFormat in the 3rd window and got GL errors as soon as I opened the program.  I then tried:

``` C++
    fmt.setVersion(2, 0);
    fmt.setProfile(QGLFormat::NoProfile);
```

To match the initial QGLFormat and now I can open multiple windows and have multiple NIFs loaded.

So, something during the OpenGL rendering is trying to set the OpenGL profile higher, and something else in the code is not happy with that.  So the next time a new window comes around, it creates a format with that profile and stops working.

I'm not sure exactly what is causing it yet, and I'll still attempt to find out, but for now I believe I've solved it sufficiently.  There is of course still the eventual possibility of rewriting the entire widget after the initial port.

**Comment by hexabits** [comment]
Regarding **Changes to QAbstractItemModel::reset()**, I believe I've confirmed that `QAbstractItemModel::reset()` does (did) nothing special.  Here is the code for it:

``` C++
#if QT_DEPRECATED_SINCE(5,0)
    QT_DEPRECATED void reset()
    {
        beginResetModel();
        endResetModel();
    }
#endif
```

So it appears to me it did nothing other than emit the private signals.  And `beginResetModel();` and `endResetModel();` just need to be called in its place which I've already done in the code.

So I think that takes care of all the previously mentioned issues.  Now it's just poking the code and seeing what falls out.

**Comment by hexabits** [comment]
I don't think my fix for the message handler is actually working:

``` C++
#if QT_VERSION >= QT_VERSION_CHECK(5, 0, 0)
void myMessageOutput(QtMsgType type, const QMessageLogContext &, const QString & str)
{
    const char * msg = str.toStdString().c_str();
#else
void myMessageOutput(QtMsgType type, const char *msg)
{
#endif
```

I think it's garbling the message encoding.   Looking into it now.   I got that fix verbatim from an article about porting from Qt 4 > Qt 5 though... so hmph.

Oh, actually it could be about the deprecation of the `QT_WA` macro.  Which I simply redefined:

``` C++
#if QT_VERSION >= 0x050000
#  define QT_WA(unicode, ansi) unicode
#endif
```

---

Fixed in jonwd7/nifskope@7b43501

**Comment by hexabits** [comment]
Re:  **QFileDialog Filter fix (So they actually filter): jonwd7/nifskope@6ca3d87**

For whatever reason the Qt 5 QFileDialog doesn't like the plain "_.filetype" filter and likes there to be parentheses so I also just added a description as well e.g. "Keyframe Files (_.kf)".

---

On that same subject, does file dragging to a blank NifSkope scene even work in the official release?  Right now my "official" release is actually the develop branch build (with all my Skyrim fixes) so I can't be 100% sure, but dragging files to the window does nothing.

I could also be misunderstanding the relevant code:

``` C++
void GLView::dragEnterEvent( QDragEnterEvent * e )
{
    if ( e->mimeData()->hasUrls() && e->mimeData()->urls().count() == 1 )
    {
        QUrl url = e->mimeData()->urls().first();
        if ( url.scheme() == "file" )
        {
            QString fn = url.toLocalFile();
            if ( textures->canLoad( fn ) )
            {
                fnDragTex = textures->stripPath( fn, model->getFolder() );
                e->accept();
                return;
            }
        }
    }

    e->ignore();
}
```

OK, after looking at the `GLView::dragMoveEvent()` it looks to be severely outdated code which is meant to let you plop textures onto meshes. 

It only works for `NiTexturingProperty` blocks it seems.

**Comment by neomonkeus** [comment]
So we should filter on the file type and decide what to do then?

**Comment by hexabits** [comment]
Yeah I need to make a ticket just to cover discussing this behavior.  I'll do that in a bit.
