### ISSUE TITLE
Confirm Quit / Discard Changes dialog

### ISSUE THREAD

**Issue by hexabits** [niftools/nifskope#29]
There should either be a setting where a user can choose to have NifSkope ask if you are sure you would like to quit, or NifSkope should detect when there have been modifications to a NIF and prompt if you would like to discard the changes.  Or both.

**Comment by neomonkeus** [comment]
:+1:  for usability. Blender has a similar feature where it saves a backup eg. file_name.blend -> file_name.blend1.
