### ISSUE TITLE
Compile error on Mac OS X

### ISSUE THREAD

**Issue by bobtedbob** [niftools/nifskope#30]
/nifskope/gl/GLee.h:765: error: typedef redefinition with different types ('int' vs 'void *')

In GLee.h the following is defined
# ifndef GL_ARB_shader_objects

```
typedef int GLhandleARB;
typedef char GLcharARB;
```
# endif

But in gltypes.h it is defined as 
# ifndef GL_ARB_shader_objects

typedef char GLcharARB;
typedef void *GLhandleARB;
# endif

This gltypes in what is on my macbook running the latest osx

**Comment by hexabits** [comment]
Hi @bobtedbob, please try compiling the GLEW branch here:  jonwd7/nifskope@df6c1e927cb09c05025ec14e73c2311fc1b91a49 

And let me know.  If GLEW is switched to at all, it will only be temporary as my experimental Qt5 branch does away with both altogether.

**Comment by hexabits** [comment]
@bobtedbob 

Closing this as the develop branch no longer uses either GLee or GLEW.  I can't say that no other GL errors exist, but this specific one cannot.
