### ISSUE TITLE
FSEngine Refactor

### ISSUE THREAD

**Issue by hexabits** [niftools/nifskope#36]
FSEngine relies on API that has become private in Qt 5.  To replace it this API first needs to be stripped out and then refactor wherever the code has assumed the virtual filesystem.  
#### [experimental/fsengine](https://github.com/jonwd7/nifskope/commits/experimental/fsengine)

I have it solved for the most part.  The "Resource Files" works just as before, ~~but there are a few other places (Spells and such) that assume the virtual filesystem.~~
##### Replace QAbstractFileEngine with QFile/QFileInfo

Everything necessary can be replicated using QFile and QFileInfo.
##### Remove FSArchiveEngine, FSArchiveHandler, BSAIterator

These were classes to extend the virtual filesystem and utilized QAbstractFileEngine, QAbstractFileEngineHandler, and QAbstractFileEngineIterator, respectively.
##### Add QByteArray member `data` to Tex struct

Each texture that gets loaded is represented as a Tex object.  For textures which load from BSAs, store the raw data directly on the Tex.  Elsewhere, check if the data is not empty.  If the data is not empty, the texture is not on the filesystem.

Wherever a QFile is assumed (to read texture data), add a QBuffer branch which will read the raw data on the Tex into memory.
##### Related
#28 Qt 5 Port
#### Tracking

Refactor Progress #32

**Comment by hexabits** [comment]
Hmm.  Should I or shouldn't I leave the old FSEngine code intact and support Qt4 / Qt5 conditionally at compile time?

I'm pretty sure my changes are all backward compatible, but the legacy code is more "pure" / simple I guess.   I'm guessing we won't have to switch back to Qt 4 for any reason so I think I would rather just strip out the old code.

**Comment by neomonkeus** [comment]
Since 4.x is depreciated and in legacy mode and this will involve less work by removing the intermediary step go for it. If we need it for whatever reason, that is the beauty of VSC ;)

**Comment by hexabits** [comment]
Yup.  See:

jonwd7/nifskope@d7aa019
jonwd7/nifskope@f167d8d

So when I do my "official" (non-experimental) commits to qt5/fsengine, I am pretty much going to copy/paste the fsengine code as of the final experimental commit.

**Comment by neomonkeus** [comment]
Excellent, makes reviewing alot easier when block refactoring of code.

**Comment by hexabits** [comment]
FSEngine refactor was complete as of jonwd7/nifskope@499b589 ... at least as far as feature parity is concerned (and then some).  Also added Skyrim auto detection for BSAs and texture paths.  And a "Remove All" button in the Resource Files window.

---

**_Note:**_ As of that commit, the codebase is still targeting Qt 4.

**Comment by neomonkeus** [comment]
If its ready to go send a pull request against develop.
