### ISSUE TITLE
BSEffectShaderProperty blocks with a Source Texture lack Edit UV support 

### ISSUE THREAD

**Issue by hexabits** [niftools/nifskope#4]
For an `NiTriShape` which contains a `BSEffectShaderProperty`, right-clicking **Texture > Edit UV** gives the error:

```
"Could not load texture data for UV editor." 
```

**Edit UV** does not show up on the `NiTriShapeData` block's context menu.

---

(Note to self: There also needs to be a recursive check so that **Edit UV** does not show on parent blocks when the child does not have a `Source Texture`)

**Comment by neomonkeus** [comment]
Closed with pull request

Ref : #9
