### ISSUE TITLE
"Create Convex Shape" spell creates broken collision

### ISSUE THREAD

**Issue by hexabits** [niftools/nifskope#6]
Related: Issue #3 

Not only does it generate it at 10x the size, I cannot get it to appear at all in the CK Preview with some meshes<sup>[1]</sup>, and despite scaling it to 0.10 in a parent NiNode, it still appears 10x larger on files where it actually worked.<sup>[2]</sup>

It does show up in my dev version where all other collision displays correctly, but it is gigantic.

~~Given the inconsistencies I believe something more is going on here than just the scaling issue.~~  (See comments)

---

**Examples:**
[1]: nordiccoffinstatic01.nif
[2]: basket01.nif

---

Sub-Issues:
- [x] The spell assumes a radius of 0.1, which is actually pretty high.  A large amount of bhkCVS have a radius of 0.00, but the vast majority use 0.05.

**Comment by hexabits** [comment]
Mmmm...  Nope, I guess that was pretty much it.  :)

I'm not certain of the reason for it simply not showing though.  Once I applied the scaledown, meshes like nordiccoffinstatic01.nif started showing in CK Preview.

**Comment by hexabits** [comment]
I did a [review of the CVS radiuses](https://gist.github.com/jonwd7/7515491) ... I can say definitively the radius should be decreased to 0.05.  There seems to be a trend with sizes too.

**Comment by neomonkeus** [comment]
Probably need to run this over the older assets and do version check.

**Comment by hexabits** [comment]
I am closing this and creating a new issue for it.  The radius can just be a user input option, like the error threshold.  I will reference this issue too.

Closed by Pull Request #9
