### ISSUE TITLE
"Set All" for various arrays (e.g. Color4 for Vertex Color arrays)

### ISSUE THREAD

**Issue by hexabits** [niftools/nifskope#66]
### Task List
- [x] Color4/Color3

**Comment by hexabits** [comment]
Vertex Color example:

![1](https://cloud.githubusercontent.com/assets/170077/3483946/7a6f8562-039a-11e4-9297-8b1a26f3c6b9.jpg)
![2](https://cloud.githubusercontent.com/assets/170077/3483947/7a6f8d82-039a-11e4-8626-00937e05697c.jpg)
![3](https://cloud.githubusercontent.com/assets/170077/3483945/7a6e91c0-039a-11e4-876c-24081ee78cfe.jpg)

**Comment by ttl269** [comment]
@jonwd7 This is good idea. More better would be to have possibility of selecting of multiple values in array (continuous area by holding shift and left click, and non-continuous holding ctrl and left click) and then setting of desired value. But even "Set all" is big step forward.
Another idea: possibility of separate setting of color only (first three components of Color4) or alpha value only (fourth component of Color4) in case of Color4 array.

**Comment by hexabits** [comment]
@ttl269  It works for either Color3 or Color4 already.  I just copy/pasted the existing Color > Choose spell and made a couple tweaks.  I could have incorporated it into the existing Spell but the spells can only have one name and "Set All" is more explicit.

Ctrl-click is something I've already looked into for many applications but there are several obstacles. I'm pretty sure the current "Spell" system isn't even equipped to deal with multiple items, so I either refactor it, or I pre-empt it with my own logic which routes each individual block index to the Spell.

However multi-select isn't extremely useful for anything vertex-related because you have to click on each and every vertex in the list to see where it is.

**Comment by hexabits** [comment]
Note to self.  I actually broke access to this with my changes to cell editing and right clicking, where too many types of cells (row/columns) could be edited, or where version-disabled rows would still have a context menu for spells.  Solution is differentiating the row which houses an array from other non-editable rows like version-disabled rows (greyed out), even though the array row is not technically editable.
