### ISSUE TITLE
Header Editor

### ISSUE THREAD

**Issue by hexabits** [niftools/nifskope#67]
There should be a separate button/command for opening up the header that is not reliant on either the Block List or Block Details view.
### Related
#18 Header strings enhancements
#37 Transform > Edit - Header String editing

**Comment by ttl269** [comment]
Agree. It is not logical and not necessary to have tree view in "Block Details". "Block Details" should really show only details of selected block in Block List. So, after loading a nif it could be empty or show details of root node of nif.
Adding button "Nif Header" aside other buttons ("Block List", "Block Details",...) would be good. Clicking on that button would open its "own area" (same as Block List, Block Details, KFM, Inspect,...) with list of expanded "NiHeader" (same as now when user expands "NiHeader").

**Comment by hexabits** [comment]
I simply implemented another tab where the Header is always present.

Animated GIF:

![blocks-header](https://cloud.githubusercontent.com/assets/170077/4910398/1b584db6-647f-11e4-96a6-97c8c85c1f39.gif)

##### Commit details

jonwd7/nifskope@28b6b93

**Comment by ttl269** [comment]
@jonwd7 The tab is perfect solution. Great!

**Comment by neomonkeus** [comment]
Agreed
