### ISSUE TITLE
Display bhkCompressedMeshShape collision

### ISSUE THREAD

**Issue by hexabits** [niftools/nifskope#7]
By far the most common collision type in Skyrim is bhkCMS. Visualizing it would be a tremendous improvement. 

I already have it done, just creating a ticket for documentation. :smiley: 

![mcusr87](https://f.cloud.github.com/assets/170077/1556279/a326577c-4ec0-11e3-8a63-8754ae9b3c94.jpg)

**Comment by neomonkeus** [comment]
Closed with pull request.

Ref : #9
