### ISSUE TITLE
Incorrect position of drawed Center of mass

### ISSUE THREAD

**Issue by ttl269** [niftools/nifskope#76]
@jonwd7 Nifskope 1.2.0 Alpha 2 draws small axes representing **Center of mass** of bhkRigidBody on wrong place for Skyrim nifs. The coords of that axes should be multiplied by `havokScale` float before drawing it. It is probably about correcting code on lines [1806](https://github.com/niftools/nifskope/blob/develop/src/gl/glnode.cpp#L1806) and [1809](https://github.com/niftools/nifskope/blob/develop/src/gl/glnode.cpp#L1809) in gl/glnode.cpp.
Fallout3 and Oblivion nifs are ok.

**Comment by hexabits** [comment]
@ttl269 Yeah I will need examples because all the meshes I'm looking at correctly show their axes.

Though if I change the Center value myself, the behavior sounds exactly the opposite of what you are saying.   If for example I change the X value to 5.0, the center moves way too far.  I assume if I were to move the parent NiNode by 5.0 that that amount is how much the center should have moved as well.

To me it sounds like I need to _divide_ by the `havokScale` value.

**Comment by ttl269** [comment]
@jonwd7 It seems to me that drawing coordinate of axis should be _multiplied_ by `havokscale` (which is set to 10.0 for Skyrim by nifskope's code).Because in order to force recent Nifskope alpha to draw center-of-mass axis on right place, I have to _multiply_ the coordinate of center of mass. Look at examples below.

**Example1** (meshes\weapons\iron\longsword.nif):
![center_of_mass_bug1a](https://cloud.githubusercontent.com/assets/2514993/6093124/e386594c-aefb-11e4-9993-3df11f9988d5.png)
Default: the center of mass is in Nifskope on wrong place comparing to CK preview.

![center_of_mass_bug1b](https://cloud.githubusercontent.com/assets/2514993/6093188/1eb2bc86-aefc-11e4-8a9f-bb1c4670801d.png)
After modifiying of Y coordinate of center of mass in Nifskope by multiplying it by 10, the axis is drawed on right place in Nifskope (the screenshot of CK preview window still shows unmodified nif, of course).

**Example 2** (meshes\clutter\food\bread01a.nif) with hidden mesh to center-of-mass axis be visible:
![center_of_mass_bug2a](https://cloud.githubusercontent.com/assets/2514993/6093198/a87ea970-aefc-11e4-8a51-1f04b7b7d2b0.png)
Default: Center-of-mass axis in Nifskope is in wrong place.

![center_of_mass_bug2b](https://cloud.githubusercontent.com/assets/2514993/6093199/af1688ca-aefc-11e4-8583-632869fd261f.png)
Modified Z part of center of mass coordinate by multipliying it by 10. Axis is in right place.

**Comment by ttl269** [comment]
Maybe to be more specific: I am talking about relationship between values stored in nif file in `Center` of bhkRigidBody (center of mass) and position where Nifskope alpha draws that small axis representing center of mass. This relationship is wrong, I think, and should be corrected by _multipliying_ the values in `Center` before the axis is drawn.

**Comment by hexabits** [comment]
@ttl269 Fixed in jonwd7/nifskope@711c5b8e3be6f88b8dc848c75611a05b4d34b661
