### ISSUE TITLE
Spell "Combine Properties" combine wrong properties

### ISSUE THREAD

**Issue by ttl269** [niftools/nifskope#77]
@jonwd7 Nifskope's spell "Combine Properties" combines properites which are not allowed to be shared (needs to be unique for each node). If it is done, it leads to CK crash.
The properties which have to be unique: `BSLightingShaderProperty`, `BSEffectShaderProperty`, `BSSkyShaderProperty`, `BSWaterShaderProperty`.
Contrary the `BSShaderTextureSet` can be shared but Niskope don't combine it (although it is not property).

**Comment by neomonkeus** [comment]
@ttl269 can you give input on this pull request #72 by @deedes

**Comment by hexabits** [comment]
OK this appears like it's going to be resolved by niftools/nifxml@72b711d ... `BSLightingShaderProperty`, `BSEffectShaderProperty`, `BSSkyShaderProperty`, `BSWaterShaderProperty` are all going to become children of `BSShaderProperty` which is already tested against in the Combine Properties spell.  See: [optimize.cpp#L64](https://github.com/niftools/nifskope/blob/9875e515e074e31704c10f1db147397ba1e33f60/src/spells/optimize.cpp#L64)
