### ISSUE TITLE
Chunk Transforms ignored

### ISSUE THREAD

**Issue by ttl269** [niftools/nifskope#82]
@jonwd7 Nifskope ignore values in `Chunk Transforms` when rendering collision meshes stored in `bhkCompressedMeshShapeData` chunks.

Each chunk has parameter `Transform Index` which chooses the item in Chunk Transforms array.

Example: I have entered value 2.0 into Z translation and value 90 to Y rotation of  Chunk 0 Transform array (originally there are zeroes).
In Nifskope it has no effect:
![collision_not_ok_in_nifskope](https://cloud.githubusercontent.com/assets/2514993/6770629/511e16c0-d0c6-11e4-99a4-7cc26edde014.png)

But in CK preview the transformation of Chunk 0 is accepted:
![collision_ok_in_ckpreview](https://cloud.githubusercontent.com/assets/2514993/6770633/689a492c-d0c6-11e4-836c-8c012640f184.jpg)

**Comment by hexabits** [comment]
Working on this now. Will probably merge to dev/2.0 shortly.

Have translation working so far:

![untitled-2](https://cloud.githubusercontent.com/assets/170077/10989858/8bf1a43a-841a-11e5-9cbf-378f04ef204d.png)
![untitled-3](https://cloud.githubusercontent.com/assets/170077/10989860/8dfd2c2c-841a-11e5-84e5-e29e65114f84.png)

**Comment by hexabits** [comment]
And rotations working:

![untitled-2a](https://cloud.githubusercontent.com/assets/170077/10990558/8727be78-8422-11e5-8066-109355f41a74.png)
![untitled-3a](https://cloud.githubusercontent.com/assets/170077/10990559/88da3048-8422-11e5-8ed9-8a297481af72.png)

@ttl269 

Do you happen to have a sampling of NIFs which didn't look correct before with the default Chunk Transform values on the mesh?  I'd like to verify they're all correct now.
