### ISSUE TITLE
3d display skewing after application reposition

### ISSUE THREAD

**Issue by Ghostwalker71** [niftools/nifskope#88]
file version NifSkope_2_0_2015-11-02
fallout 3 files were used to duplicate issue
Open two instances of nifskope by selecting two nif files, r/click, open. When repositioning the first instance the 3d view screen resizes correctly but the second instance will retain the original aspect ratio and fill the remaining open space with a copy image.

**Comment by hexabits** [comment]
Hmm.  It seems that you don't even need to open two files, just one file and an additional empty window. 

Also, it's always the last window that still works, no matter the number.  The rest will stop working, and as you close the working one the previously opened window will work again.

**Comment by Ghostwalker71** [comment]
Looks like it's working correctly now, all instances resize and update normally.
