### ISSUE TITLE
NifSkope 2.0.0 Pre-alpha 5, When refresh the “Connect Points”, NifSkope crash.

### ISSUE THREAD

**Issue by g2mXagent** [niftools/nifskope#94]
NifSkope 2.0.0 Pre-alpha 5
Windows 7 SP1 64bit
Fallout 4
## process reproduce:
1. File -> Open, choose "shackwalloutercrnout05b.nif" ( or any NIF ).
2. in Block List, right mouse button on "0 NiNode" -> Node -> Attach Extra Data -> "BSConnectPoint::Parents"
3. select "BSConnectPoint::Parents"
4. in Block Details, change "Num Connect Points" to 1, or any number
5. click the "green icon" on the right side "Connect Points" node
6. crash!

**Comment by hexabits** [comment]
Yeah, you're not using the latest version.  I fixed this on 2016-04-20.

https://github.com/jonwd7/nifskope/releases/tag/v2.0.dev5
