### ISSUE TITLE
¿Anyone know how to solve it?

### ISSUE THREAD

**Issue by shaffervanity** [niftools/nifskope#97]
fo4_env.frag:

ERROR: 0:2: '' :  extension 'GL_ARB_shader_texture_lod' is not supported

fo4_env.prog:

depends on shader fo4_env.frag which was not compiled successful
ob_normalmap_vcol_e.prog:

The fragment shader uses varying D, but geometry shader does not write to it.
The fragment shader uses varying A, but geometry shader does not write to it.

ob_parallax+glowmap.prog:

The fragment shader uses varying HalfVector, but geometry shader does not write to it.

ob_parallax.prog:

The fragment shader uses varying HalfVector, but geometry shader does not write to it.

ob_parallax_vcol_ad.prog:

The fragment shader uses varying HalfVector, but geometry shader does not write to it.

**Comment by hexabits** [comment]
FYI this isn't the place to make issues for dev releases.  That would be on my GitHub or the forums. 

---

I've fixed the ob_*.prog errors which will be in the next release.  This only happens on certain Intel integrated graphics as far as I know.

The lack of `GL_ARB_shader_texture_lod` support also indicates that you are probably on integrated graphics.  Is your graphics chipset listed in red on this page?

http://feedback.wildfiregames.com/report/opengl/feature/GL_ARB_shader_texture_lod

There's nothing you can really do if your hardware and drivers do not support it.  If you could let me know what your graphics chipset is I can see if there is possibly any workaround or alternative extension.  I could make the support for the extension optional but then reflections wouldn't look right in the FO4 shaders.

**Comment by hexabits** [comment]
I'm closing this since it should never have been made.
